### ISSUE TITLE
App jumping position when changing between pages with and without a scroll-bar.

### ISSUE THREAD

**Issue by evclen** [ScottLogic/Technology-Carbon-Standard#14]
In Chrome
When the app is full-screen such that the content has margins either side of it.
Switching between tabs "Technology Carbon Standard" which as a scroll bar and "About" which does not have a scroll bar causes the content and nav bar to jump position slightly to the right.
This also happens when switching between other pages with and without scroll bars such as Operational emissions and downstream emissions.

**Comment by dkrees** [comment]
Thank you for raising this issue. This has been fixed and resolved now.
