### ISSUE TITLE
Small CSS bug with folks using the Extension Privacy Badger

### ISSUE THREAD

**Issue by JStrachanSL** [ScottLogic/Technology-Carbon-Standard#15]
When browsing the https://www.techcarbonstandard.org/ website anytime it uses the Creative Commons link that produces 4 icons it bugs out when the user is using the privacy extension Privacy Badger. The extension seems to block the icons from properly appearing as it seems to deem them part of a tracker. In Firefox developers edition this shows as an overflow of text like : 
![image](https://github.com/ScottLogic/Technology-Carbon-Standard/assets/54021747/06caa216-edd7-4465-9201-53f69561d091)
In Chrome it also blocks the images appearing but it just shows up as 4 broken image icons. 

If you disable Privacy Badger for the website the icons come back and then if you enable it again, and reload, the images are still there and this is because the images get cached. I've double-checked and specifically, this endpoint is getting blocked : https://mirrors.creativecommons.org/presskit/icons/

I know this isn't very high on the priority list as it's only going to majorly affect a very small minority of users but you probably at least want to know about it. Feel free to close!

**Comment by cronky** [comment]
Thanks for raising this - it is a bit niche but it will be annoying for users of privacy badger. @dkrees if this is a quick fix can we sort?

**Comment by jcamilleri-scottlogic** [comment]
I've raised this in our internal bug tracking and will get this investigated shortly.

**Comment by mgriffin-scottlogic** [comment]
I've had a look at this today and it appears to be rendering fine on both browsers now. It looks as if the Privacy Badger team have acknowledged that this can cause an issue and it only attempts to block cookies from this domain now. If you decide to block it completely I have only seen it remove the icons and there is also a red warning triangle that blocking this domain is known to break websites.
