### ISSUE TITLE
Commercial Off The Shelf (COTS) Software vs Open Source

### ISSUE THREAD

**Issue by mgifford** [ScottLogic/Technology-Carbon-Standard#22]
I think USA courts have determined that open source is a kind of [Commercial Off The Shelf (COTS) Software](https://www.techcarbonstandard.org/categories/upstream#commercial-software).

However, most folks think of MS Office when they think COTS and not Firefox. 

Should this be clarified?

**Comment by cronky** [comment]
Excellent point and one we were thinking of tweaking - thanks for this
