### ISSUE TITLE
Add a social card

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/Technology-Carbon-Standard#29]
Currently when you share the TCS website, the social card isn't very appealing:

<img width="1163" alt="image" src="https://github.com/ScottLogic/Technology-Carbon-Standard/assets/1098110/a34b0980-3607-415b-9d36-ab43926ab751">

**Comment by jcamilleri-scottlogic** [comment]
I've raised this in our internal feature request tool and will investigate as soon as we are able.
