### ISSUE TITLE
Add a link to GitHub

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/Technology-Carbon-Standard#30]
Currently the TCS website doesn't appear to have a link to this GitHub repo. I'd suggest adding a GitHub logo in the header that links to this project.

You might also want to consider adding links to pages that allow people to submit fixes / make edits to the page content.

**Comment by jcamilleri-scottlogic** [comment]
Raised in our internal feature request tool.

**Comment by sdun-scottlogic** [comment]
Tested & Approved - SD.

**Comment by mgriffin-scottlogic** [comment]
The live site now has a link to this repository in the header and footer. We've added a separate feature request to cover the suggestion to add page specific links.
